<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <base href="/">
    <title>johnpfisk.com</title>
    <meta name="author" content="johnpfisk.com">
    <meta name="description" content="The home of johnpfisk on the web.">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/forestryio/ubuild-blocks@1.0.0/dist/css/ubuild.css"/>
  </head>
  <body>

<!-- Add your site or application content here -->
<p>---
title: johnpfisk.com
author: johnpfisk.com
email: john@johnpfisk.com
description: The home of johnpfisk on the web.
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
timezone: Australia/Sydney
</p>

  </body>
</html>